### ISSUE TITLE
Unable to sign in on a new local instance

### ISSUE THREAD

**Issue by akrolsmir** [ForumMagnum/ForumMagnum#6016]
Hey there! I'm trying to get started with a local dev instance, in order to test https://github.com/ForumMagnum/ForumMagnum/pull/6015.

I've been able to create a local mongo instance and access an empty localhost:3000: 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/856034/199622450-e4d80ea0-eceb-4fba-aa6c-5a6927e6cdc0.png">

But can't seem to sign up or log in; I get an error indicating auth0 isn't set up correctly? I'm redirected to `http://localhost:3000/auth/auth0?screen_hint=signup&returnTo=/`, with an error:

```
Error: Unknown authentication strategy "auth0"
    at attempt (/Users/austin/Code/ForumMagnum/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate2 (/Users/austin/Code/ForumMagnum/node_modules/passport/lib/middleware/authenticate.js:369:34)
    at /Users/austin/Code/ForumMagnum/packages/lesswrong/server/authenticationMiddlewares.ts:431:10
    at /Users/austin/Code/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:51:27
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at /Users/austin/Code/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:34:33
    at /Users/austin/Code/ForumMagnum/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:22:21
    at Layer.handle [as handle_request] (/Users/austin/Code/ForumMagnum/node_modules/router/lib/layer.js:102:15)
    at trim_prefix (/Users/austin/Code/ForumMagnum/node_modules/router/index.js:330:13)
    at /Users/austin/Code/ForumMagnum/node_modules/router/index.js:294:7
    at Function.process_params (/Users/austin/Code/ForumMagnum/node_modules/router/index.js:349:12)
    at next (/Users/austin/Code/ForumMagnum/node_modules/router/index.js:285:10)
    at /Users/austin/Code/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:100:12
    at /Users/austin/Code/ForumMagnum/packages/lesswrong/server/authenticationMiddlewares.ts:235:25
    at allFailed (/Users/austin/Code/ForumMagnum/node_modules/passport/lib/middleware/authenticate.js:110:18)
    at attempt (/Users/austin/Code/ForumMagnum/node_modules/passport/lib/middleware/authenticate.js:183:28)`
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1203289968458977) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/628521446211730/1203289968458977

**Comment by Xodarap** [comment]
It might be easier for you to test in less wrong mode so you don't need to use auth zero? (`yarn start`). Or you could make a auth0 account to just use for testing; here's the database structure:
![image](https://user-images.githubusercontent.com/221511/200131711-6214aa04-1a35-4184-9739-8ab66b751919.png)
