### ISSUE TITLE
 Unable to Run Client/Server After Following README Documentation

### ISSUE THREAD

**Issue by Slyracoon23** [ForumMagnum/ForumMagnum#7274]
### Description:

I am unable to start the local development server after following the README instructions for setup. The issue arises when running `yarn start-local-db`. The startup process fails with an error message indicating an uninitialized SQL client. However, the instructions in the README did not mention the need for SQL configuration and it seems that the project should be using MongoDB instead.

### Steps to reproduce:

1. Set up a local MongoDB instance and ran `sudo mongod --dbpath ./myLocalDatabase`
2. Executed `yarn start-local-db` command

### Expected result:

The local development server should have started without any issues and connected to the MongoDB instance.

### Actual result:

An error message appears in the terminal indicating an uninitialized SQL client:

```
2023-05-28T12:49:07.587Z: Unhandled rejection
2023-05-28T12:49:07.587Z: Error: SQL Client is not initialized
    at getSqlClientOrThrow (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/lib/sql/sqlClient.ts:9:11)
    at initPostgres (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:110:41)
    at initServer (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:170:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at serverStartup (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:177:32)
2023-05-28T12:49:07.588Z: Error: SQL Client is not initialized
    at getSqlClientOrThrow (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/lib/sql/sqlClient.ts:9:11)
    at initPostgres (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:110:41)
    at initServer (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:170:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at serverStartup (/home/slyracoon23/Documents/blog/ForumMagnum/packages/lesswrong/server/serverStartup.ts:177:32)
```

### Environment:

- OS: Ubuntu 22
- Node version: 18.12.1
- Yarn version: 1.22.18
- MongoDB version: v6.0.6

Please assist me in addressing this issue. It would seem that either the README documentation needs to be updated or the application has an incorrect dependency on an SQL client.

---

**Comment by darkruby501** [comment]
Ah, our bad. The codebase was recently migrated from MongoDB to Postgres and we haven't updated the instructions accordingly. @oetherington

**Comment by Slyracoon23** [comment]
> Ah, our bad. The codebase was recently migrated from MongoDB to Postgres and we haven't updated the instructions accordingly. @oetherington

Ok, got it! Is it worth waiting on the updated repo?

**Comment by darkruby501** [comment]
Not sure. I'd see what @oetherington says.

**Comment by NoamDev** [comment]
I managed to make it work with docker:
```
docker run --name fm-postgres -e POSTGRES_PASSWORD=mysecretpassword -v ./schema/accepted_schema.sql:/accepted_schema.sql -p5432:5432 -d postgres
docker exec -u postgres fm-postgres psql -f /accepted_schema.sql
yarn start-local-db --postgresUrl 'postgres://localhost:5432?user=postgres&password=mysecretpassword'
```
What do you think? I can create a PR to add this to README.md if you want.

**Comment by david-mears-2** [comment]
Thanks for that, @NoamDev.

After the last instruction, I get a lot of `error: relation "X" does not exist` errors.

**Comment by NoamDev** [comment]
I think the second command should have dealt with that...
What was the output from the second one?

**Comment by david-mears-2** [comment]
A load of `CREATE TABLE`.

**Comment by david-mears-2** [comment]
For example:

```
2023-07-17T18:19:29.089Z: error: relation "Posts" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '436',
  routine: 'RangeVarGetRelidExtended',
  query: `CREATE INDEX IF NOT EXISTS "idx_posts_pingbackPosts" ON "Posts" USING gin ( "status" , "isFuture" , "draft" , "unlisted" , "shortform" , "hiddenRelatedQuestion" , "authorIsUnreviewed" , "groupId" , ("pingbacks"->'Posts') , "baseScore" , "_id" , "meta" , "isEvent" , "af" , "frontpageDate" , "curatedDate" , "postedAt" )`,
  params: undefined
}
```

**Comment by NoamDev** [comment]
That's odd, from what I gather this should happen because the table Posts doesn't exist, but the second command should have created it.
Can you make sure it actually exists? At least that the log contains CREATE TABLE Posts and there's no error after that?

**Comment by NoamDev** [comment]
Another idea is that there was a recent commit that affected the schema, maybe this broke some things?
Maybe even reset to as far as about the time I first commented in this issue to be sure.

**Comment by david-mears-2** [comment]
Thanks for your help so far - it's supererogatory. I'm guessing that somehow the commands are trying to act on different databases.

> docker exec -u postgres fm-postgres psql -f /accepted_schema.sql

<details>
  <summary>output</summary>
<code>
psql:/accepted_schema.sql:18: ERROR:  relation "AdvisorRequests" already exists
psql:/accepted_schema.sql:32: ERROR:  relation "Bans" already exists
psql:/accepted_schema.sql:53: ERROR:  relation "Books" already exists
psql:/accepted_schema.sql:68: ERROR:  relation "Chapters" already exists
psql:/accepted_schema.sql:80: ERROR:  relation "ClientIds" already exists
psql:/accepted_schema.sql:96: ERROR:  relation "Collections" already exists
psql:/accepted_schema.sql:107: ERROR:  relation "CommentModeratorActions" already exists
psql:/accepted_schema.sql:185: ERROR:  relation "Comments" already exists
psql:/accepted_schema.sql:200: ERROR:  relation "Conversations" already exists
psql:/accepted_schema.sql:210: ERROR:  relation "CronHistories" already exists
psql:/accepted_schema.sql:220: ERROR:  relation "DatabaseMetadata" already exists
psql:/accepted_schema.sql:236: ERROR:  relation "DebouncerEvents" already exists
psql:/accepted_schema.sql:248: ERROR:  relation "DigestPosts" already exists
psql:/accepted_schema.sql:260: ERROR:  relation "Digests" already exists
psql:/accepted_schema.sql:273: ERROR:  relation "EmailTokens" already exists
psql:/accepted_schema.sql:286: ERROR:  relation "FeaturedResources" already exists
psql:/accepted_schema.sql:308: ERROR:  relation "GardenCodes" already exists
psql:/accepted_schema.sql:318: ERROR:  relation "Images" already exists
psql:/accepted_schema.sql:332: ERROR:  relation "LWEvents" already exists
psql:/accepted_schema.sql:342: ERROR:  relation "LegacyData" already exists
psql:/accepted_schema.sql:372: ERROR:  relation "Localgroups" already exists
psql:/accepted_schema.sql:385: ERROR:  relation "Messages" already exists
psql:/accepted_schema.sql:397: ERROR:  relation "Migrations" already exists
psql:/accepted_schema.sql:411: ERROR:  relation "ModerationTemplates" already exists
psql:/accepted_schema.sql:422: ERROR:  relation "ModeratorActions" already exists
psql:/accepted_schema.sql:442: ERROR:  relation "Notifications" already exists
psql:/accepted_schema.sql:457: ERROR:  relation "PageCache" already exists
psql:/accepted_schema.sql:468: ERROR:  relation "PetrovDayLaunchs" already exists
psql:/accepted_schema.sql:480: ERROR:  relation "PodcastEpisodes" already exists
psql:/accepted_schema.sql:491: ERROR:  relation "Podcasts" already exists
psql:/accepted_schema.sql:504: ERROR:  relation "PostEmbeddings" already exists
psql:/accepted_schema.sql:520: ERROR:  relation "PostRecommendations" already exists
psql:/accepted_schema.sql:532: ERROR:  relation "PostRelations" already exists
psql:/accepted_schema.sql:698: ERROR:  relation "Posts" already exists
psql:/accepted_schema.sql:715: ERROR:  relation "RSSFeeds" already exists
psql:/accepted_schema.sql:728: ERROR:  relation "ReadStatuses" already exists
psql:/accepted_schema.sql:746: ERROR:  relation "Reports" already exists
psql:/accepted_schema.sql:762: ERROR:  relation "ReviewVotes" already exists
psql:/accepted_schema.sql:792: ERROR:  relation "Revisions" already exists
psql:/accepted_schema.sql:814: ERROR:  relation "Sequences" already exists
psql:/accepted_schema.sql:822: ERROR:  relation "Sessions" already exists
psql:/accepted_schema.sql:843: ERROR:  relation "Spotlights" already exists
psql:/accepted_schema.sql:857: ERROR:  relation "Subscriptions" already exists
psql:/accepted_schema.sql:871: ERROR:  relation "TagFlags" already exists
psql:/accepted_schema.sql:892: ERROR:  relation "TagRels" already exists
psql:/accepted_schema.sql:947: ERROR:  relation "Tags" already exists
psql:/accepted_schema.sql:960: ERROR:  relation "UserActivities" already exists
psql:/accepted_schema.sql:971: ERROR:  relation "UserMostValuablePosts" already exists
psql:/accepted_schema.sql:985: ERROR:  relation "UserRateLimits" already exists
psql:/accepted_schema.sql:999: ERROR:  relation "UserTagRels" already exists
psql:/accepted_schema.sql:1207: ERROR:  relation "Users" already exists
psql:/accepted_schema.sql:1227: ERROR:  relation "Votes" already exists
</code>
</details>

> yarn start-local-db --postgresUrl 'postgres://localhost:5432?user=postgres&password=mysecretpassword'

<details>
<summary>output</summary>
<code>
yarn run v1.22.19
$ ./build.js -run --watch --settings settings.json --postgresUrl 'postgres://localhost:5432?user=postgres&password=mysecretpassword'
Wrote ./build/server/js/serverBundle.js (22.3MB, 3.2s)
Watching files for changes...
Running node --inspect -r source-map-support/register -- ./build/... [23008]
Debugger listening on ws://127.0.0.1:9229/7a305330-a38f-429b-8bb6-5e10f403f029
For help, see: https://nodejs.org/en/docs/inspector
Wrote ./build/client/js/bundle.js (19.2MB, 3.6s)
(node:22999) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
No setting value provided for public instance setting for setting with name sentry.url despite it being marked as warning
No setting value provided for public instance setting for setting with name sentry.environment despite it being marked as warning
No setting value provided for public instance setting for setting with name sentry.release despite it being marked as warning
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
Loading settings from Mongo...
Analytics event: serverStarted { '[[time of day]]': '10:28:15.317' }
Running in non-cluster mode
Starting server
2023-07-18T09:28:17.576Z: Warning loading branch dbs: ENOENT: no such file or directory, open './.branchdbcache' /Users/davidmears/projects/ForumMagnum
2023-07-18T09:28:17.576Z: Connecting to postgres (localhost:5432?user=postgres&password=mysecretpassword)
2023-07-18T09:28:17.577Z: Connecting to postgres with a connection-pool max size of 25
2023-07-18T09:28:18.298Z: SQL syntax error: relation "Posts" does not exist CREATE OR REPLACE FUNCTION fm_post_tag_similarity(
    post_id_a TEXT,
    post_id_b TEXT
  )
    RETURNS FLOAT LANGUAGE sql IMMUTABLE AS
   'SELECT
      COALESCE(SUM(LEAST(a, b))::FLOAT / SUM(GREATEST(a, b))::FLOAT, 0) AS similarity
    FROM (
      SELECT
        GREATEST((a."tagRelevance"->"tagId")::INTEGER, 0) AS a,
        GREATEST((b."tagRelevance"->"tagId")::INTEGER, 0) AS b
      FROM (
        SELECT JSONB_OBJECT_KEYS("tagRelevance") AS "tagId"
        FROM "Posts"
        WHERE "_id" IN (post_id_a, post_id_b)
      ) "allTags"
      JOIN "Posts" a ON a."_id" = post_id_a
      JOIN "Posts" b ON b."_id" = post_id_b
    ) "tagRelevance";'

2023-07-18T09:28:18.300Z: SQL syntax error: relation "Posts" does not exist CREATE OR REPLACE FUNCTION fm_post_tag_ids(post_id TEXT)
    RETURNS TEXT[] LANGUAGE sql IMMUTABLE AS
   'SELECT ARRAY_AGG(tags."tagId")
    FROM "Posts" p
    JOIN (
      SELECT JSONB_OBJECT_KEYS("tagRelevance") AS "tagId"
      FROM "Posts"
      WHERE "_id" = post_id
    ) tags ON p."_id" = post_id
    WHERE (p."tagRelevance"->tags."tagId")::INTEGER >= 1;'

2023-07-18T09:28:18.301Z: Failed to run Postgres onConnectQuery: error: relation "Posts" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) {
  length: 105,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '473',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable',
  query: 'CREATE OR REPLACE FUNCTION fm_post_tag_similarity(\n' +
    '    post_id_a TEXT,\n' +
    '    post_id_b TEXT\n' +
    '  )\n' +
    '    RETURNS FLOAT LANGUAGE sql IMMUTABLE AS\n' +
    "   'SELECT\n" +
    '      COALESCE(SUM(LEAST(a, b))::FLOAT / SUM(GREATEST(a, b))::FLOAT, 0) AS similarity\n' +
    '    FROM (\n' +
    '      SELECT\n' +
    '        GREATEST((a."tagRelevance"->"tagId")::INTEGER, 0) AS a,\n' +
    '        GREATEST((b."tagRelevance"->"tagId")::INTEGER, 0) AS b\n' +
    '      FROM (\n' +
    '        SELECT JSONB_OBJECT_KEYS("tagRelevance") AS "tagId"\n' +
    '        FROM "Posts"\n' +
    '        WHERE "_id" IN (post_id_a, post_id_b)\n' +
    '      ) "allTags"\n' +
    '      JOIN "Posts" a ON a."_id" = post_id_a\n' +
    '      JOIN "Posts" b ON b."_id" = post_id_b\n' +
    `    ) "tagRelevance";'\n` +
    '  ',
  params: undefined
}
2023-07-18T09:28:18.302Z: Loading settings
2023-07-18T09:28:18.302Z: Loading settings from Postgres...
2023-07-18T09:28:18.304Z: SQL syntax error: relation "DatabaseMetadata" does not exist SELECT * from "DatabaseMetadata" WHERE "name" = 'serverSettings'
2023-07-18T09:28:18.306Z: Failed to load database settings from Postgres - trying Mongo...
2023-07-18T09:28:18.306Z: Loading settings from Mongo...
2023-07-18T09:28:18.325Z: No setting value provided for public instance setting for setting with name faqPostId despite it being marked as warning
2023-07-18T09:28:18.325Z: No setting value provided for public instance setting for setting with name contactPostId despite it being marked as warning
2023-07-18T09:28:18.339Z: No setting value provided for public instance setting for setting with name expectedDatabaseId despite it being marked as warning
2023-07-18T09:28:20.959Z: SQL syntax error: relation "DatabaseMetadata" does not exist SELECT * from "DatabaseMetadata" WHERE "name" = 'publicSettings'
2023-07-18T09:28:20.966Z: SQL syntax error: relation "DatabaseMetadata" does not exist SELECT * from "DatabaseMetadata" WHERE "name" = 'databaseId'
2023-07-18T09:28:21.231Z: Building postgres tables
2023-07-18T09:28:21.241Z: Initializing switching collections from lock table
2023-07-18T09:28:21.245Z: SQL syntax error: relation "Posts" does not exist
  CREATE MATERIALIZED VIEW IF NOT EXISTS "UniquePostUpvoters" AS
    SELECT
      p."_id" AS "postId",
      ARRAY_AGG(DISTINCT ('x' || SUBSTR(MD5(v."userId"), 1, 8))::BIT(32)::INTEGER)
        AS "voters"
    FROM "Posts" p
    INNER JOIN "Votes" v ON
      p."_id" = v."documentId" AND
      v."collectionName" = 'Posts' AND
      v."cancelled" IS NOT TRUE AND
      v."isUnvote" IS NOT TRUE AND
      v."voteType" IN ('smallUpvote', 'bigUpvote')
    GROUP BY p."_id"

2023-07-18T09:28:21.245Z: Failed to ensure Postgres views exist: error: relation "Posts" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 105,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '217',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable',
  query: '\n' +
    '  CREATE MATERIALIZED VIEW IF NOT EXISTS "UniquePostUpvoters" AS\n' +
    '    SELECT\n' +
    '      p."_id" AS "postId",\n' +
    `      ARRAY_AGG(DISTINCT ('x' || SUBSTR(MD5(v."userId"), 1, 8))::BIT(32)::INTEGER)\n` +
    '        AS "voters"\n' +
    '    FROM "Posts" p\n' +
    '    INNER JOIN "Votes" v ON\n' +
    '      p."_id" = v."documentId" AND\n' +
    `      v."collectionName" = 'Posts' AND\n` +
    '      v."cancelled" IS NOT TRUE AND\n' +
    '      v."isUnvote" IS NOT TRUE AND\n' +
    `      v."voteType" IN ('smallUpvote', 'bigUpvote')\n` +
    '    GROUP BY p."_id"\n',
  params: undefined
}
2023-07-18T09:28:21.246Z: Running onStartup functions
2023-07-18T09:28:21.248Z: Sentry is not configured. To activate error reporting, please set the sentry.url variable in your settings file.
2023-07-18T09:28:21.258Z: SQL syntax error: relation "CronHistories" does not exist CREATE INDEX IF NOT EXISTS "idx_CronHistories_startedAt" ON "CronHistories" USING btree ( "startedAt" )
2023-07-18T09:28:21.258Z: SQL Error for CronHistories at position undefined: relation "CronHistories" does not exist: `CREATE INDEX IF NOT EXISTS "idx_CronHistories_startedAt" ON "CronHistories" USING btree ( "startedAt" )`: []: {
  collectionName: 'CronHistories',
  fieldOrSpec: { startedAt: 1 },
  options: { expireAfterSeconds: 172800 }
}
2023-07-18T09:28:21.262Z: Unhandled rejection
2023-07-18T09:28:21.262Z: error: relation "CronHistories" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 111,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '436',
  routine: 'RangeVarGetRelidExtended',
  query: 'CREATE INDEX IF NOT EXISTS "idx_CronHistories_startedAt" ON "CronHistories" USING btree ( "startedAt" )',
  params: undefined
}
2023-07-18T09:28:21.271Z: error: relation "CronHistories" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
2023-07-18T09:28:21.321Z: SQL syntax error: relation "DatabaseMetadata" does not exist SELECT "DatabaseMetadata".* FROM "DatabaseMetadata" WHERE "name" =  'karmaInflationSeries' LIMIT 1
2023-07-18T09:28:21.322Z: SQL Error for DatabaseMetadata at position 34: relation "DatabaseMetadata" does not exist: `SELECT "DatabaseMetadata".* FROM "DatabaseMetadata" WHERE "name" =  $1 LIMIT $2`: [ 'karmaInflationSeries', 1 ]: {
  collectionName: 'DatabaseMetadata',
  selector: { name: 'karmaInflationSeries' },
  options: undefined,
  projection: undefined
}
2023-07-18T09:28:21.322Z: Unhandled rejection
2023-07-18T09:28:21.322Z: error: relation "DatabaseMetadata" does not exist
    at Parser.parseErrorMessage (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/davidmears/projects/ForumMagnum/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Socket.emit (/Users/davidmears/projects/ForumMagnum/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 115,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '34',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable',
  query: `SELECT "DatabaseMetadata".* FROM "DatabaseMetadata" WHERE "name" =  'karmaInflationSeries' LIMIT 1`,
  params: undefined
}
</code>

etc etc etc
</details>

**Comment by NoamDev** [comment]
If you stop the postgres, and try to run the server, does it complain the postgres is down?
I'm asking to make sure there is only one postgres instance

**Comment by NoamDev** [comment]
Otherwise, yeah, multiple dbs sounds like it would explain this, but then why did it just work like that for me? Only thing I can think of is that something changed in the code since I ran this.

**Comment by david-mears-2** [comment]
Yeah, it seems like `yarn start-local-db --postgresUrl 'postgres://localhost:5432?user=postgres&password=mysecretpassword'` is connecting to my postgres db, not the docker one, given that it does the same regardless if the docker container is running or not.

**Comment by david-mears-2** [comment]
Nice, we got there. For posterity, this worked for me:

```
docker run --name fm-postgres -e POSTGRES_PASSWORD=mysecretpassword -v ~/projects/ForumMagnum/schema/accepted_schema.sql:/accepted_schema.sql -p5433:5432 -d postgres
docker exec -u postgres fm-postgres psql -f /accepted_schema.sql
yarn start-local-db --postgresUrl 'postgres://localhost:5433?user=postgres&password=mysecretpassword'
```
