### ISSUE TITLE
Sometimes Db collection fields are nullable, but the TypeScript interface doesn't match, leading to hard-to-find bugs

### ISSUE THREAD

**Issue by michaelkeenan** [ForumMagnum/ForumMagnum#7951]
The Waking Up staging forum had a weird bug where an admin changed the postedAt of their post to null, and then the admin account stopped working: you couldn't log in as that account, and the profile page 404ed.

The cause turned out to be that the `UsersProfile` fragment depends on the user's posts all having non-null postedAt values (we sort all the posts by postedAt so that we can tally votes on the user's 20 most recent documents).

Once found, that's easily fixed, and that's not what this issue is about. It was *very* hard to figure out why the user account no longer worked; my prior on a post being able to curse its owner's account in this way was low, and between the user object returning null rather than throwing an error, and all the indirection between a `useMulti` call to get a `UsersProfile` and the line with the bug, it took me a whole day to find that the account was broken because of a particular post, and longer still to figure out the rest.

I fear this unexpectedly null value might not be the only problem of its kind, so finding and preventing this kind of bug is what this issue is about. Calling a function on a nullable field should be impossible due to TypeScript. In this case, TypeScript didn't catch it because the DbPost interface has `postedAt: Date` where it should be `postedAt: Date | null`. Might other nullable fields have a similar mismatch? The Db[Collection] interfaces are generated by `generateDbTypes.sh`, and maybe that script has a bug where it doesn't set nullability correctly. (I'd look into it myself but should really prioritize other things this month, hence this detailed write-up.)

(Relatedly: when an error occurs in a resolver, should Node catch it and just return null, or should it throw an exception further up the chain? It’d have been much easier to find this problem if the exception hadn’t been caught.)

**Comment by michaelkeenan** [comment]
This comment is for my notes on the details of the postedAt null error.

The `UsersProfile` fragment includes `SunshineUsersList`
`SunshineUsersList` includes `recentKarmaInfo`
`recentKarmaInfo` is a userResolver that calls the rateLimitUtils function `getRecentKarmaInfo`
`getRecentKarmaInfo` calls `calculateRecentKarmaInfo`
`calculateRecentKarmaInfo` calls `getVotesOnLatestDocuments`
`getVotesOnLatestDocuments` sorts votes like this, calling getTime() on postedAt, which fails when postedAt is null:

`const sortedVotes = votes.sort((a, b) => b.postedAt.getTime() - a.postedAt.getTime())`

Calling getTime() on a null causes an error. The error gets caught by by some Node thing, so instead of throwing the exception up to the user, it just returns a null user for the UsersProfile fragment.

Here’s the stack trace:
```
"TypeError: Cannot read properties of null (reading 'getTime')",
'    at /Users/michaelkeenan/Programming/projects/ForumMagnum2/packages/lesswrong/lib/rateLimits/utils.ts:110:46',
'    at Array.sort (<anonymous>)',
'    at getVotesOnLatestDocuments (/Users/michaelkeenan/Programming/projects/ForumMagnum2/packages/lesswrong/lib/rateLimits/utils.ts:107:29)',
'    at calculateRecentKarmaInfo (/Users/michaelkeenan/Programming/projects/ForumMagnum2/packages/lesswrong/lib/rateLimits/utils.ts:129:30)',
'    at getRecentKarmaInfo (/Users/michaelkeenan/Programming/projects/ForumMagnum2/packages/lesswrong/server/rateLimitUtils.ts:234:10)',
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
```

So of course the immediate fix here is to fix `getVotesOnLatestDocuments` to not call getTime() on a nullable field.

**Comment by michaelkeenan** [comment]
I speculate that [whatever this problem was](https://github.com/ForumMagnum/ForumMagnum/issues/7893), where a particular comment couldn't be agree-voted (though now it can, idk why) is the kind of thing that could be caused by fragments depending on unexpectedly nullable fields.

**Comment by b0b3rt** [comment]
> that script has a bug where it doesn't set nullability correctly

Yeah, the script only generates `| null` for database types when a field explicitly has `nullable: true` set in its schema definition, even though database fields are nullable by default.  I think ideally we'd make the `nullable` flag required in field schema definitions, backfill all existing fields, and fix any type errors that inevitably show up when we regenerate correct database types.
